# General settings
title: Makbule Gulcin Ozsoy 
title_html: "<b>Makbule Gulcin Ozsoy<br/>Makbule Gülçin Özsoy</b>"
description: I'm a PostDoc at UCD, Dublin, Ireland #Makbule Gülçin Özsoy
baseurl: ""
url: "https://mgulcin.com"

# Author
author: Makbule Gulcin Ozsoy 
email: first-two-names@gmail.com
twitter_username: #
github_username: mgulcin
github_displayname: github
keybase_username: #
linkedin_username: makbulegulcinozsoy
linkedin_displayname: linkedin
author_website: #
google_scholar_username: Cmbcf_UAAAAJ 
google_scholar_displayname: google_scholar 
rss: #
curriculum:
    url: assets/Cv_MakbuleGulcinOzsoy.pdf
user_picture: mgozsoy.jpg

# Favicon
favicon:
  safari: 5bbad5
  theme: ffffff

# Build settings
markdown: kramdown
theme: academic 
remote_theme: gaalcaras/academic
#gems:
#  - jekyll-feed
#exclude:
#  - jekyll_build.sh
#  - Gemfile
#  - Gemfile.lock
