# General settings
title: Makbule Gulcin Ozsoy 
title_html: "<b>Makbule Gulcin Ozsoy</b>"
description: Makbule Gülçin Özsoy
baseurl: ""
url: "https://mgulcin.com"

# Author
author: Makbule Gulcin Ozsoy
email: makbulegulcin -at- gmail.com
twitter_username: #
github_username: mgulcin
github_displayname: Github
keybase_username: #
linkedin_username: makbulegulcinozsoy
linkedin_displayname: LinkedIn
author_website: #
google_scholar_username: Cmbcf_UAAAAJ 
google_scholar_displayname: Google Scholar 
rss: #
curriculum:
    name: CV
    url: assets/Cv_Resume.pdf
user_picture: mgozsoy.jpg

# Favicon
favicon:
  safari: 5bbad5
  theme: ffffff

# Build settings
markdown: kramdown
# theme: academic 
remote_theme: gaalcaras/academic
#gems:
#  - jekyll-feed
#exclude:
#  - jekyll_build.sh
#  - Gemfile
#  - Gemfile.lock
